/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yunsoft_study_JniOne */

#ifndef _Included_com_yunsoft_study_JniOne
#define _Included_com_yunsoft_study_JniOne
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yunsoft_study_JniOne
 * Method:    getValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yunsoft_study_JniOne_getValue
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
